### PR TITLE
Travis deploys master to gh-pages

### LINKED ISSUE #1: Auto-deploy to GitHub pages
Set up travis to deploy the app to `gh-pages` branch.

### PR DESCRIPTION
**Pull request by jamesarosen**
Resolves #1

### CODE REVIEW

**Comment by jamesarosen** [comment]
[This Travis build](https://travis-ci.org/glimmerjs/todomvc-demo/builds/219091994) is worth looking at. Some caveats worth thinking through when reviewing this:

 1. It didn't finish the deploy step because there were no changes to deploy.
 2. It used an `after_success` hook instead of a `deploy` hook because the `deploy` hook is configured to only run on master.

**Review by mmun — CHANGES_REQUESTED** [review]
Looks good to me. We can iterate if there's any bugs. It blows my mind every time that this is so complicated :P

Can you please configure `yarn` to use the `--frozen-lockfile` option?

**Comment by jamesarosen** [comment]
> Can you please configure yarn to use the --frozen-lockfile option?

I think that's the default now: https://github.com/travis-ci/travis-build/pull/997

**Comment by mmun** [comment]
Ok, let's find out! :)

**Review by mmun — APPROVED** [review]

**Comment by jamesarosen** [comment]
Ah, nope. It _was_ the default briefly. https://github.com/travis-ci/travis-build/pull/1000 reverted it.

**Comment by mmun** [comment]
Indeed. https://travis-ci.org/glimmerjs/todomvc-demo/builds/219095504#L202

> success Saved lockfile.

**Comment by jamesarosen** [comment]
Resolved in #13. See https://travis-ci.org/glimmerjs/todomvc-demo/builds/219095993#L202

**Pull request merged**
