### PR TITLE
add favicon

### PR DESCRIPTION
**Pull request by jamesarosen**

### CODE REVIEW

**Comment by mmun** [comment]
Did you try a transparent background? The logo on https://github.com/glimmerjs/ was supposed to have a transparent background :P

**Comment by mmun** [comment]
The logo on https://github.com/glimmerjs/ was supposed to have a transparent background :P

**Comment by mmun** [comment]
I'll merge for now until we get the vectors...

**Comment by jamesarosen** [comment]
> Did you try a transparent background?

I didn't. I don't know where to find the source for that icon.

**Pull request merged**
