### PR TITLE
Add simple routing

### PR DESCRIPTION
**Pull request by michalsnik**
This PR implements simple routing as pointed in #3

### CODE REVIEW

**Comment by Martodox** [comment]
Could https://github.com/tildeio/route-recognizer be a better alternative?

**Comment by michalsnik** [comment]
I think it doesn't really matter in this case. I used the simplest solution, and all alternatives might look quite the same so.. but I'll be happy to hear what other guys think as well :)

**Comment by Martodox** [comment]
@michalsnik I think it would be nice to use other TS based components with glimmer, navigo is written with pure JS. 
But it is just my opinion :)

**Comment by MartinMalinda** [comment]
ui router is written in TS but there is very little info on how to use it standalone. And TodoMVC seems to prescribe Flatiron Director:

https://github.com/tastejs/todomvc/blob/master/app-spec.md

> Routing is required for all implementations. If supported by the framework, use its built-in capabilities. Otherwise, use the Flatiron Director routing library located in the /assets folder.

**Comment by mmun** [comment]
This looks great! There's two things we can iterate on in the future:
- Where should the routing logic be handled?
  - With the current approach of wiring up the router in the component constructor and assigning the tracked properties directly in the handlers is elegant and concise so I say we keep it that way for now.
- Using director
  - I'm not sure if director is compatible with rollup at  the moment, but we can switch to it once the `app.import` stuff lands.

**Pull request merged**
